# Generated by Django 5.2 on 2025-04-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aaronscaletty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='terminalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='terminalform',
            name='terminal_input',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
